-- Records the git branch a task delivered its work on.
--
-- Worktree-mode local_directory tasks hand their result back as a branch in the
-- user's own repo rather than as edits to the working copy, so the branch name
-- is the only pointer to where the work went. It is written on BOTH terminal
-- paths: a task that fails partway still commits whatever the agent produced,
-- and that is exactly when the user most needs to be told where to look.
--
-- Nullable and unindexed on purpose: only worktree tasks populate it, and it is
-- read alongside the task row that is already being fetched by primary key.
ALTER TABLE agent_task_queue ADD COLUMN IF NOT EXISTS branch_name TEXT;
